# $Id: tmcs_startup.pl.tpl,v 1.77 2008-11-08 22:51:11 molson Exp $
#
#
# app server dev environment
# generated by '/mgr/shared/deployment/bin//build.pl app1.shared.dev7.websys.tmcs' on 2016-03-21 11:27:28
#

use lib qw ( /app/shared/conf/perl /app/shared/lib/perl );
use strict;
use warnings;

use Apache2::Access ();
use Apache2::Connection ();
use Apache2::ConnectionUtil ();
use Apache2::RequestIO ();
use Apache2::RequestRec ();
use Apache2::RequestUtil ();
use Apache2::Response ();
use Apache2::ServerRec ();
use Apache2::ServerUtil ();
use Apache2::SubRequest ();
use Apache2::URI ();
use Apache2::Util ();
use Apache2::Const -compile => qw(:common :http);
use Apache2::Log;

use Carp;

1;

